import type { Metadata } from 'next';

import { Header } from '@/layouts/Header';
import './globals.css';

export const metadata: Metadata = {
  title: 'Zustand Todo',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <Header />
        <main className="">{children}</main>
      </body>
    </html>
  );
}
