import { MantineColorsTuple, MantineProvider, createTheme } from '@mantine/core';
import type { Metadata } from 'next';

import '@mantine/core/styles.css';
import '@mantine/dates/styles.css';
import './globals.css';

const myColor: MantineColorsTuple = [
  '#e1f9ff',
  '#ccedff',
  '#9ad7ff',
  '#64c1ff',
  '#3baefe',
  '#20a2fe',
  '#099cff',
  '#0088e4',
  '#0078cd',
  '#0069b6',
];
const theme = createTheme({
  colors: {
    myColor,
  },
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="container">
        <MantineProvider theme={theme}>{children}</MantineProvider>
      </body>
    </html>
  );
}
